import { Check, ChevronDown, CircleHelp, Clock3, MessageCircle, Zap } from "lucide-react";
import type { Service } from "@/components/site-data";

type RequestBuilderProps = { service: Service; services: Service[]; checkedDocuments: string[]; readyPercent: number; whatsappUrl: string; onServiceChange: (serviceId: string) => void; onToggleDocument: (document: string) => void; };

export default function RequestBuilder({ service, services: serviceOptions, checkedDocuments, readyPercent, whatsappUrl, onServiceChange, onToggleDocument }: RequestBuilderProps) {
  const Icon = service.icon;
  return <div id="request-builder" className="request-shell scroll-mt-28">
    <div className="request-topbar"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center bg-[#ffd21f] text-[#07101f]"><Zap className="h-4 w-4" /></span><div><p className="text-sm font-black text-white">Build your request</p><p className="mt-0.5 text-xs text-blue-200">A quick preparation check</p></div></div><span className="inline-flex items-center gap-2 text-xs font-bold text-emerald-300"><span className="h-2 w-2 animate-pulse bg-emerald-400" /> Support available</span></div>
    <div className="grid lg:grid-cols-[0.82fr_1.18fr]">
      <div className="border-b border-slate-200 bg-[#f4f7fb] p-5 sm:p-6 lg:border-b-0 lg:border-r"><label htmlFor="service-select" className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">1. Select service</label><div className="relative mt-3"><select id="service-select" value={service.id} onChange={(event) => onServiceChange(event.target.value)} className="h-12 w-full appearance-none border border-slate-300 bg-white px-4 pr-10 text-sm font-black text-[#071f4f] outline-none focus:border-[#0857d6] focus:ring-4 focus:ring-blue-100">{serviceOptions.map((option) => <option key={option.id} value={option.id}>{option.title}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /></div><div className="mt-6 border border-slate-200 bg-white p-5"><span className={"service-icon service-icon-" + service.accent}><Icon className="h-6 w-6" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.16em] text-slate-400">{service.category}</p><h2 className="mt-2 text-xl font-black text-[#071f4f]">{service.title}</h2><p className="mt-2 text-xs font-semibold leading-5 text-[#0857d6]">{service.localTitle}</p><p className="mt-4 text-sm leading-6 text-slate-600">{service.description}</p></div></div>
      <div className="bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">2. Check what you have</p><h3 className="mt-2 text-lg font-black text-[#071f4f]">Starter document list</h3></div><span className="readiness" aria-live="polite">{readyPercent}% ready</span></div><div className="mt-4 h-1.5 overflow-hidden bg-slate-100" aria-hidden="true"><div className="h-full bg-[#0857d6] transition-all duration-500" style={{ width: readyPercent + "%" }} /></div><div className="mt-5 grid gap-2">{service.documents.map((document) => { const checked = checkedDocuments.includes(document); return <button key={document} type="button" onClick={() => onToggleDocument(document)} className={"document-check " + (checked ? "document-check-active" : "")} aria-pressed={checked}><span className="check-box"><Check className="h-3.5 w-3.5" /></span><span>{document}</span></button>; })}</div><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-slate-500"><CircleHelp className="mt-0.5 h-3.5 w-3.5 shrink-0" /> Exact requirements may vary. We confirm them before work begins.</p><a href={whatsappUrl} target="_blank" rel="noreferrer" className="primary-button mt-5 h-12 w-full justify-center"><MessageCircle className="h-[18px] w-[18px]" /> Send prepared request</a></div>
    </div>
    <div className="request-footnote"><Clock3 className="h-4 w-4" /> No form submission happens on this website. Start by confirming the requirement with us.</div>
  </div>;
}
